In [72]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv('BostonHousing.csv')
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [4]:
df.corr()

crim        zn     indus      chas       nox        rm       age  \
crim     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219433  0.352734   
zn      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311173 -0.569537   
indus    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.394193  0.644779   
chas    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091468  0.086518   
nox      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302751  0.731470   
rm      -0.219433  0.311173 -0.394193  0.091468 -0.302751  1.000000 -0.240286   
age      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240286  1.000000   
dis     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.203507 -0.747881   
rad      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.210718  0.456022   
tax      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292794  0.506456   
ptratio  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.357612  0.261515   
b       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128107 -0.273534   
lstat    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.615721  0.602339   
medv    -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.696169 -0.376955   

              dis       rad       tax   ptratio         b     lstat      medv  
crim    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
zn       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
indus   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
chas    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
nox     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
rm       0.203507 -0.210718 -0.292794 -0.357612  0.128107 -0.615721  0.696169  
age     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
dis      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
rad     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
tax     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
ptratio -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
b        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
lstat   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
medv     0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

In [39]:
df.iloc[:,:-1]

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [48]:
df['rm'].isnull().sum()
df['rm'].fillna(df['rm'].mean(),inplace=True)
df['rm'].isnull().sum()

0

In [64]:
X = df.loc[:,['rm','crim']]
y = df['medv'] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mse

41.96417783029148

In [65]:
r2

0.4277647214988345

In [66]:
new_data = pd.DataFrame([[6.421, 0.02731]], columns=['rm', 'crim'])
y_ans = model.predict(new_data)
y_ans

array([24.63526902])

In [75]:
model.coef_

array([ 8.69962233, -0.26004109])

In [68]:
model.intercept_

-31.217904226527864

<b>MAKING OWN LINEAR REGRESSION CLASS<b/>

In [84]:
class MeraLR:

    def __init__(self):
     self.coef_ = None
     self.intercept_ = None
    
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        #calculate the coeff
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
        print(betas)
    
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred
      

In [85]:
lr = MeraLR()
lr.fit(X_train,y_train)

[-31.21790423   8.69962233  -0.26004109]


In [86]:
df.loc[:,['rm','crim']]

rm     crim
0    6.575  0.00632
1    6.421  0.02731
2    7.185  0.02729
3    6.998  0.03237
4    7.147  0.06905
..     ...      ...
501  6.593  0.06263
502  6.120  0.04527
503  6.976  0.06076
504  6.794  0.10959
505  6.030  0.04741

[506 rows x 2 columns]

In [87]:
lr.predict(X_test)

array([24.57500606, 27.55946675, 20.80443942, 21.52147503, 22.23996419,
       23.3806224 , 20.14889894, 22.41791807, 21.9218907 , 21.15637152,
       20.5247643 , 20.97041084, -3.80017683, 22.9834602 , 18.36570915,
       28.29707726, 19.90156399,  7.5089017 , 37.28803044, 20.1633131 ,
       23.02558384, 25.15230162, 18.18898106, 26.12241941, 19.20586549,
       13.9001097 , 19.86186768, 24.83922004, 20.58647808, 19.11791771,
       17.22020927, 24.64228596, 27.30326204, 14.47298234, 19.85595408,
       17.88936452, 31.28178568, 19.83126761, 21.50127379, 23.06042778,
       15.59775222, 28.35298387, 38.66963733, 17.41253711, 24.59539193,
       16.67259303, 18.07914813, 24.58462102, 21.30180256, 25.98046912,
       21.02757931, 29.39142963, 21.89468326, 27.74450688, 33.62772235,
       22.73880674, 21.41155797, 28.46109793, 24.35082735, 17.49372526,
       23.42059661, 31.84224889, 25.66714031, 16.03849761, 25.9962378 ,
       15.15957499, 22.81063865, 23.59760078, 26.14892009, 19.55

In [88]:
n_d = pd.DataFrame([[6.421, 0.02731]],columns=['rm', 'crim'])
lr.predict(n_d)

array([24.63526902])